# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  myawesomecontainerapp:
    image: myawesomecontainerapp
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5099:5099
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
